version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    working_directory: ~/laravel-ci-3/backend
    steps:
      - checkout:
          path: ~/laravel-ci-3/backend
      - run: sudo composer self-update --1
      - run: composer install -n --prefer-dist
      - run: yarn install --frozen-lockfile
      - run: yarn run dev
      - run:
          name: php test
          command: vender/bin/phpunit
