name: reviewdog

on:
  pull_request:
    branches:
      - main

defaults:
  run:
     working-directory: ./backend

jobs:
  # 構文チェック
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: code sniffer install
        run: composer require squizlabs/php_codesniffer --dev
      - name: lint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: run: ./vendor/bin/phpcs --report=emacs --standard=phpcs.xml ./app | reviewdog -reporter=github-pr-review -efm='%f:%l:%c:%m'

  # 静的解析
  analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: phpstan install
        run: composer require phpstan/phpstan --dev
      - name: analyse
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./vendor/bin/phpstan analyse --error-format=raw --no-progress -l 5 ./app | reviewdog -reporter=github-pr-review -f=phpstan
